### ISSUE TITLE
Server error on Login

### ISSUE THREAD

**Issue by ricardopacheco** [topac/rmega#20]
```
require "rmega"
storage = Rmega.login("your@email.com", "your_password")
```

result

```
Rmega::ServerError: Object (typically, node or user) not found
    from /cache/gems/rmega-0.2.2/lib/rmega/session.rb:150:in `block in request'
    from /cache/gems/rmega-0.2.2/lib/rmega/net.rb:7:in `survive'
    from /cache/gems/rmega-0.2.2/lib/rmega/session.rb:144:in `request'
    from /cache/gems/rmega-0.2.2/lib/rmega/session.rb:94:in `login'
    from /cache/gems/rmega-0.2.2/lib/rmega.rb:33:in `login'
    from (irb):6
    from /cache/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
    from /cache/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
    from /cache/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /cache/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /cache/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by topac** [comment]
Hi, it simply means that the email and/or the password are wrong

**Comment by ricardopacheco** [comment]
I'm sure the data is correct, as did several times trying and with the same data could log-in in browser.

**Comment by topac** [comment]
Which version are you using?

**Comment by topac** [comment]
Try this 

```ruby
require "rmega"
Rmega.logger.level = ::Logger::DEBUG
storage = Rmega.login("your@email.com", "your_password")
```

to view debug logging

**Comment by ricardopacheco** [comment]
Right, i will doing that.
```
rmega (0.2.2)
```
