### ISSUE TITLE
ERROR: `read_configuration_file': undefined method `exists?' for File:Class (NoMethodError)`

### ISSUE THREAD

**Issue by NikitaSavc** [topac/rmega#44]
Hello, I'm trying to upload file. And I have issue with "exists?"
```
nikita@nikita-desktop:~/LineageOS> rmega-up.ruby3.2 out/target/product/j4lte/lineage-17.1-20230514-UNOFFICIAL-j4lte.zip -u micraftur@gmail.com
/usr/lib64/ruby/gems/3.2.0/gems/rmega-0.3.1/lib/rmega/cli.rb:30:in `read_configuration_file': undefined method `exists?' for File:Class (NoMethodError)

        return {} unless File.exists?(configuration_filepath)
                             ^^^^^^^^
Did you mean?  exist?
	from /usr/lib64/ruby/gems/3.2.0/gems/rmega-0.3.1/lib/rmega/cli.rb:9:in `cli_options'
	from /usr/lib64/ruby/gems/3.2.0/gems/rmega-0.3.1/bin/rmega-up:11:in `<top (required)>'
	from /usr/bin/rmega-up.ruby3.2:25:in `load'
	from /usr/bin/rmega-up.ruby3.2:25:in `<main>'
```
How to solve it? 
Thank you.

**Comment by topac** [comment]
I see, `.exists?` was deprecated but `.exist?` ramains

**Comment by NikitaSavc** [comment]
@topac , thanks.
